### ISSUE TITLE
User Information Fails to save after edit

### ISSUE THREAD

**Issue by kenpole** [cyber-republic/CyberRepublic#107]
I've noticed on the forum that my full name appears, now, and I sought to change it so that I didn't have my full name so obvious.  However, on going to the CR website, under "my republic", and trying to edit my profile, it fails to save, only greying out the button but not completing the save (brave browser and chrome).  I have not tested it with other browsers besides these two.

**Comment by luckyyang** [comment]
Will look into it, thanks for the feedback

**Comment by luckyyang** [comment]
@kenpole I tested with my account on chrome, I can change my first and last name. Could you tell me your username so I can help look into the issue?

**Comment by kenpole** [comment]
kenninja Kenneth Kao is my account info.  I've been trying to make it
Kenneth K.

**Comment by luckyyang** [comment]
Found the root cause, it's due to we changed the validation rule for social media fields, we only accept url now for them to avoid potential attack. If you want to bypass the err, you need input url for every social field.

I will talk with Mike about the design, cause not all social media username are urls. We will improve it, for now please use url, thanks.

**Comment by luckyyang** [comment]
Bug fixed. UX issue we will use another story to track it.
