### ISSUE TITLE
🙏 Create develop branch

### ISSUE THREAD

**Issue by jmsaulnier** [cyber-republic/CyberRepublic#44]
It would be nice to create a "develop" branch so when developers submit PR, they know in which branch to merge
Right now there is a bunch of branches (some looks like are not used anymore, it would be nice to remove them)

_See branches_
**develop** ⟶ dev server
**staging** ⟶ staging env
**master** ⟶ production env

**Comment by luckyyang** [comment]
@jmsaulnier Thanks for the advice. Right now we have a simplified branch workflow which is similar to what you mentioned, we have:
staging -> dev/staging env
master -> production env

There is no dev env now due to we have limited man power and it will reduce the maintenance cost, we just finished the workflow, checkout here:
https://docs.google.com/document/d/12W_iTCFrlxq2THHYRvAJD6S0XZq1CoewtBbv5wiD9G0/edit?usp=sharing

Feel free to add your comments.
