### ISSUE TITLE
⚠️ Secure API endpoints / user information

### ISSUE THREAD

**Issue by jmsaulnier** [cyber-republic/CyberRepublic#56]
For example https://api.cyberrepublic.org/api/task/list/ give too much information about users (ex:  wallet address, logins) 
 
I don't have enough knowledge about API security, but I'm not sure creating an API accessible via client side for this project is the best idea, API calls should be on the server side in my opinion (with for example API Keys)

**Comment by luckyyang** [comment]
For the credential info, I will look into it, normally should NOT send back these info back from API especially they are not used.

For the concern of "API accessible via client side", all the APIs with http `GET` method will be accessible via client (browser) because that's how browser works(use http GET method to get web page content), such as this api `https://api.cyberrepublic.org/api/task/list/`. So it should not be a security issue, right?

![image](https://user-images.githubusercontent.com/1963646/52575426-25a44380-2e59-11e9-8acb-b4eb543f3711.png)

**Comment by jmsaulnier** [comment]
What I'm worried to have everything on the client side with open source API repository is typically in this situation where the REST API is very verbose and you can have a potential data leak.
For now there is not really sensitive information so it's not such a big deal, but something to consider for the future for sure

**Comment by luckyyang** [comment]
Got it, thanks!

**Comment by jmsaulnier** [comment]
@luckyyang something worth considering in the future as well is to switch to GraphQL

**Comment by luckyyang** [comment]
I do not see much benefits using GraphQL for current project. It should be more suitable if later CR becomes an platform for developers to build their app/dapps.
